name: Documentation
on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - Update JS documentation
      - Update C# documentation
jobs:
  js:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - name: Conditional run
        id: cond-run
        run: |
          if("${{ github.event.action }}" -ne "Update JS documentation") {
            Write-Output "::set-output name=skip::true"
            Write-Output "Step skipped."
          }
      - name: Setup Node.js
        uses: actions/setup-node@v1
        if: ${{ steps.cond-run.outputs.skip != 'true' }}
        with:
          node-version: 12.x
      - name: Checkout repository
        uses: actions/checkout@v2
        if: ${{ steps.cond-run.outputs.skip != 'true' }}
        with:
          persist-credentials: false
          repository: altmp/altv-types
          ref: ${{ github.event.client_payload.sha }}
          path: ./altv-types
      - name: Install dependencies
        if: ${{ steps.cond-run.outputs.skip != 'true' }}
        run: |
          Set-Location -Path "./altv-types/docs/"
          yarn install
      - name: Generate JS metadata
        if: ${{ steps.cond-run.outputs.skip != 'true' }}
        run: |
          Set-Location -Path "./altv-types/docs/"
          Push-Location -Path "../"
          npx typedoc --options "./docs/typedoc.json"
          Pop-Location
          npx type2docfx "./api/.manifest" "./api/" --basePath "." --sourceUrl "https://github.com/altmp/altv-types" --sourceBranch "${{ github.event.client_payload.sha }}" --disableAlphabetOrder
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: ${{ steps.cond-run.outputs.skip != 'true' }}
        with:
          name: js
          path: ./altv-types/docs/
  cs:
    runs-on: windows-2016
    continue-on-error: true
    steps:
      - name: Conditional run
        id: cond-run
        run: |
          if("${{ github.event.action }}" -ne "Update C# documentation") {
            Write-Output "::set-output name=skip::true"
            Write-Host "Step skipped." -ForegroundColor "Red"
          }
      - name: Checkout repository
        uses: actions/checkout@v2
        if: ${{ steps.cond-run.outputs.skip != 'true' }}
        with:
          persist-credentials: false
          repository: FabianTerhorst/coreclr-module
          ref: ${{ github.event.client_payload.sha }}
          path: ./coreclr-module
      - name: Download DocFx package
        uses: robinraju/release-downloader@v1
        if: ${{ steps.cond-run.outputs.skip != 'true' }}
        with:
          repository: dotnet/docfx
          tag: v2.56.7
          fileName: docfx.zip
      - name: Unzip DocFx package
        if: ${{ steps.cond-run.outputs.skip != 'true' }}
        run: |
          Expand-Archive -Path "./docfx.zip" -DestinationPath "./docfx/"
          Remove-Item -Path "./docfx.zip"
      - name: Generate C# metadata
        if: ${{ steps.cond-run.outputs.skip != 'true' }}
        run: ./docfx/docfx metadata "./coreclr-module/docs/docfx.json" --property TargetFramework=netcoreapp3.1
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: ${{ steps.cond-run.outputs.skip != 'true' }}
        with:
          name: cs
          path: ./coreclr-module/docs/
  docs:
    runs-on: windows-latest
    needs:
      - js
      - cs
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Checkout JS repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: altmp/altv-types
          path: ./altv-types
      - name: Checkout C# repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: FabianTerhorst/coreclr-module
          path: ./coreclr-module
      - name: Download DocFx package
        uses: robinraju/release-downloader@v1
        with:
          repository: dotnet/docfx
          tag: v2.56.7
          fileName: docfx.zip
      - name: Unzip DocFx package
        run: |
          Expand-Archive -Path "./docfx.zip" -DestinationPath "./docfx/"
          Remove-Item -Path "docfx.zip"
      - name: Download DocFx TypeScriptReference package
        uses: robinraju/release-downloader@v1
        with:
          repository: Lhoerion/DocFx.Plugins.TypeScriptReference
          tag: v1.1.2
          fileName: docfx-plugins-typescriptreference.zip
      - name: Unzip DocFx TypeScriptReference package
        run: |
          Expand-Archive -Path "./docfx-plugins-typescriptreference.zip" -DestinationPath "./templates/"
          Remove-Item -Path "./docfx-plugins-typescriptreference.zip"
      - name: Download DocFx ExtractSearchIndex package
        uses: robinraju/release-downloader@v1
        with:
          repository: Lhoerion/DocFx.Plugins.ExtractSearchIndex
          tag: v1.0.0
          fileName: docfx-plugins-extractsearchindex.zip
      - name: Unzip DocFx ExtractSearchIndex package
        run: |
          Expand-Archive -Path "./docfx-plugins-extractsearchindex.zip" -DestinationPath "./templates/"
          Remove-Item -Path "./docfx-plugins-extractsearchindex.zip"
      - name: Download DocFx DiscordFX package
        uses: robinraju/release-downloader@v1
        with:
          repository: Lhoerion/DiscordFX
          latest: true
          fileName: docfx-tmpls-discordfx.zip
      - name: Unzip DocFx DiscordFX package
        run: |
          Expand-Archive -Path "./docfx-tmpls-discordfx.zip" -DestinationPath "./templates/"
          Remove-Item -Path "./docfx-tmpls-discordfx.zip"
      - run: npm install adm-zip
      - name: Download previous job artifacts
        uses: actions/github-script@v4
        with:
          script: |
            const AdmZip = require("adm-zip");
            const fs = require("fs");
            const path = require("path");
            const artifactNames = ["js", "cs"];
            const artifacts = (await github.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            })).data.artifacts;
            if (!artifacts.length) {
              console.log("No artifacts found");
              return;
            }
            for (const artifact of artifactNames.map(el => artifacts.find(el2 => el2.name === el))) {
              if (!artifact) continue;
              console.log("==> Artifact:", artifact.id);
              console.log(`==> Downloading: ${artifact.name}.zip (${(artifact.size_in_bytes / 1000000).toFixed(2)}MB)`);
              const zip = await github.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
                archive_format: "zip"
              });
              const filePath = path.join("./", artifact.name);
              const adm = new AdmZip(Buffer.from(zip.data));
              adm.getEntries().forEach((entry) => {
                const action = entry.isDirectory ? "creating" : "inflating";
                console.log(`  ${action}: ${path.join(filePath, entry.entryName)}`);
              })
              adm.extractAllTo(filePath, true);
            }
      - name: Download current job artifacts
        uses: actions/download-artifact@v2
      - name: Unpack artifacts
        run: |
          Remove-Item -Path "./altv-types/docs/" -Recurse
          if(-not (Test-Path -Path "./js/js.tar")) {
            Move-Item -Path "./js/"  -Destination "./altv-types/docs"
          } else {
            Move-Item -Path "./js/js.tar"  -Destination "./altv-types/js.tar"
            tar -xvf "./altv-types/js.tar" -C "./altv-types/"
            Remove-Item -Path "./altv-types/js.tar"
          }
          if([System.String]::IsNullOrWhiteSpace((Get-Content -Path "altv-types\docs\api\.manifest" -ErrorAction SilentlyContinue))) {
            throw "Invalid altv-types repo manifest."
          }
          Remove-Item -Path "./coreclr-module/docs/" -Recurse
          if(-not (Test-Path -Path "./cs/cs.tar")) {
            Move-Item -Path "./cs/"  -Destination "./coreclr-module/docs"
          } else {
            Move-Item -Path "./cs/cs.tar"  -Destination "./coreclr-module/cs.tar"
            tar -xvf "./coreclr-module/cs.tar" -C "./coreclr-module/"
            Remove-Item -Path "./coreclr-module/cs.tar"
          }
          if([System.String]::IsNullOrWhiteSpace((Get-Content -Path "coreclr-module\docs\api\.manifest" -ErrorAction SilentlyContinue))) {
            throw "Invalid coreclr-module repo manifest."
          }
      - name: Build docs
        run: ./docfx/docfx "./docfx.json"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: ./_site/
  deploy:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - docs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: site
          path: ./docs/_site
      - name: Deploy page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
          cname: docs.altv.mp
          full_commit_message: Deploying to gh-pages from @ ${{ github.sha }} 🚀
      - name: Post Download artifacts
        if: ${{ always() }}
        uses: geekyeggo/delete-artifact@v1
        with:
          name: site
      - name: Download previous job artifacts
        uses: actions/github-script@v4
        with:
          result-encoding: json
          script: |
            const fs = require("fs");
            const path = require("path");
            const artifactNames = ["js", "cs"];
            const artifacts = (await github.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            })).data.artifacts;
            if (!artifacts.length) {
              console.log("No artifacts found");
              return;
            }
            for (let i = artifacts.length - 1; i >= 0; i--) {
              const artifact = artifacts[i];
              if (!artifact || artifacts.reduce((acc, val) => (val.name === artifact.name ? ++acc : acc), 0) <= 1) continue;
              console.log("==> Artifact:", artifact.id);
              console.log(`==> Removing: ${artifact.name}.zip (${(artifact.size_in_bytes / 1000000).toFixed(2)}MB)`);
              await github.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id
              });
              artifact.name = null;
            }
